### ISSUE TITLE
Left align text

### ISSUE THREAD

**Issue by DanielThaumazo** [thaumazo/www.thaumazo.org#13]
Let's switch from Center aligned text to Left aligned text.

**Comment by ken-spencer** [comment]
I've tried left as well, but seems a bit off to me. Perhaps if the header was left too. Could be a bit of a rabit hole to line everything up.  Some before after screen shots to illustrate.  Of course the links don't line up nicely in the original, so perhaps we are already going down the hole :)
<img width="1381" alt="Screenshot 2024-09-26 at 9 55 01 AM" src="https://github.com/user-attachments/assets/6e3d06dc-5a81-4731-863d-e87b3f1db79b">
<img width="1381" alt="Screenshot 2024-09-26 at 9 50 14 AM" src="https://github.com/user-attachments/assets/11d70ba7-cf36-4dc2-b290-a707d19967cd">

**Comment by ken-spencer** [comment]
Have aligned the text.
