### ISSUE TITLE
Update tag type content to be in kebab case. 

### ISSUE THREAD

**Issue by ken-spencer** [thaumazo/www.thaumazo.org#3]
Doing a quick review of the content,  one change I think we need is to convert any of the data that might link to a page from title case to kebab case. For example:
liaison: [“Daniel Lindenberger”, “Travis Vandenberg”]
should be
liaison: [“daniel-lindenberger”, “travis-vandenberg”]
Then in the people section we would have “daniel-lindenberger.md” With Daniel’s bio in the file (etc). 
If we do it this way, we can both look up the info for daniel and also have the info we need to link back to Daniel’s page for anyone who wants to learn more. Could also use this to calculate the reverse and list various things Daniel (as the example, but also everyone) is associated with on his page.
I think this reasoning will apply to any named thing that will also have a page such as partners. If this makes sense, we could potentially have Rae update this and also make placeholder files for each person, partner etc as they go. Could contain as little  information as the name.  Let me know if there is anything I overlooked here.

Also thinking if they don't have a bio I can easilly convert back to sentence case on the fly and just display their name or organization etc. 

Potentially of interest to:  @DanielThaumazo

**Comment by ken-spencer** [comment]
Also note, if we commit and push with a message like: 
Resolves #3: Update tag type content to be in kebab case

It will automatically resolve the issue and also import your changes into this discussion.

**Comment by DanielThaumazo** [comment]
My understanding is this is complete. Can someone confirm and mark it as such if true?

**Comment by ken-spencer** [comment]
Think the commit node was "resolves" not "resolved" on that one @rae-thaumazo. Resolving.
